#! /bin/sh

PATH=/sbin:/bin:/usr/bin
KERNELVER=2.6.20.16
export PATH
export KERNELVER


mount -t proc proc /proc
mount -t tmpfs -o size=12288k tmpfs /var
mount -t tmpfs -o size=16k tmpfs /mnt

mkdir /var/tmp
mkdir /var/tmp/adsl

LOADTYPE=$(cat /proc/csp/loadtype)
if [ "$LOADTYPE" = "3" ];then
echo "=============init normal mode================!!!"
/etc/init.norm
elif [ "$LOADTYPE" = "2" ];then
echo "=============init debug mode==================!!!"
/etc/init.debug
else
echo "loadtype para is error!!!"
exit 0
fi







